var NODE_TYPE_ARXIU_FISIC = "udl:placaArxiuFisic";
var NODE_TYPE_FOLDER = "cm:folder";
var FOLDER_ARXIU_FISIC = "Espacio de empresa/Sitios/af/documentLibrary";
var namespaceUDL = "{http://www.smile.com/model/udl/1.0}";
var namespaceUDLRM = "{http://www.smile.com/model/udlrm/1.0}";
var ASPECT_RM_FONS = "{http://www.smile.com/model/udlrm/1.0}fons";
var ASPECT_RM_SERIE = "{http://www.smile.com/model/udlrm/1.0}serie";
var TYPE_FONS = "udl:fons";
var TYPE_SERIE = "udl:serie";