<?xml version="1.0" encoding="UTF-8"?>

<response>
	<service>modificarDocument</service>
	<username>${username}</username>
	<success>${success}</success>
	<#if error?exists>   
		<error>${error}</error>
	</#if>
	<#if document?exists>   
		<document>
			<id>${document.id}</id>
			<name>${document.name}</name>
			<path>${document.displayPath}</path>	
			<tipus>${document.type}</tipus>		
			<metadades>
				<#if document.type == 'udl:document'>
					<tipus_entitat_document>${document.properties['udl:tipus_entitat_document']}</tipus_entitat_document>
					<categoria_document>${document.properties['udl:categoria_document']}</categoria_document>													
					<secuencial_identificador_document>${document.properties['udl:secuencial_identificador_document']}</secuencial_identificador_document>
					<esquema_identificador_document>${document.properties['udl:esquema_identificador_document']}</esquema_identificador_document>
					<nom_natural_document>${document.properties['udl:nom_natural_document']}</nom_natural_document>
					<data_inici_document>${document.properties['udl:data_inici_document']}</data_inici_document>
					<data_fi_document>${document.properties['udl:data_fi_document']}</data_fi_document>					
					<descripcio_document>${document.properties['udl:descripcio_document']}</descripcio_document>														
					<classificacio_acces_document>${document.properties['udl:classificacio_acces_document']}</classificacio_acces_document>
					<codi_politica_control_acces_document>${document.properties['udl:codi_politica_control_acces_document']}</codi_politica_control_acces_document>
					<sensibilitat_dades_caracter_personal_document>${document.properties['udl:sensibilitat_dades_caracter_personal_document']}</sensibilitat_dades_caracter_personal_document>
					<tipus_acces_document>${document.properties['udl:tipus_acces_document']}</tipus_acces_document>
					<idioma_document>${document.properties['udl:idioma_document']}</idioma_document>
					<valoracio_document>${document.properties['udl:valoracio_document']}</valoracio_document>													
					<tipus_dictamen_document>${document.properties['udl:tipus_dictamen_document']}</tipus_dictamen_document>
					<accio_dictaminada_document>${document.properties['udl:accio_dictaminada_document']}</accio_dictaminada_document>
					<suport_origen_document>${document.properties['udl:suport_origen_document']}</suport_origen_document>
					<nom_format_document>${document.properties['udl:nom_format_document']}</nom_format_document>
					<versio_format_document>${document.properties['udl:versio_format_document']}</versio_format_document>										
					<nom_aplicacio_creacio_document>${document.properties['udl:nom_aplicacio_creacio_document']}</nom_aplicacio_creacio_document>
					<versio_aplicacio_creacio_document>${document.properties['udl:versio_aplicacio_creacio_document']}</versio_aplicacio_creacio_document>
					<registre_formats_document>${document.properties['udl:registre_formats_document']}</registre_formats_document>
					<resolucio_document>${document.properties['udl:resolucio_document']}</resolucio_document>
					<dimensions_fisiques_document>${document.properties['udl:dimensions_fisiques_document']}</dimensions_fisiques_document>
					<tamany_logic_document>${document.properties['udl:tamany_logic_document']}</tamany_logic_document>
					<quantitat_document>${document.properties['udl:quantitat_document']}</quantitat_document>
					<unitats_document>${document.properties['udl:unitats_document']}</unitats_document>
					<suport_document>${document.properties['udl:suport_document']}</suport_document>
					<localitzacio_document>${document.properties['udl:localitzacio_document']}</localitzacio_document>
					<algoritme_document>${document.properties['udl:algoritme_document']}</algoritme_document>
					<valor_document>${document.properties['udl:valor_document']}</valor_document>
					<tipus_signatura_document>${document.properties['udl:tipus_signatura_document']}</tipus_signatura_document>
					<format_signatura_document>${document.properties['udl:format_signatura_document']}</format_signatura_document>
					<rol_signatura_document>${document.properties['udl:rol_signatura_document']}</rol_signatura_document>
					<tipus_documental_document>${document.properties['udl:tipus_documental_document']}</tipus_documental_document>
					<denominacio_estat_document>${document.properties['udl:denominacio_estat_document']}</denominacio_estat_document>
					<tipus_copia_document>${document.properties['udl:tipus_copia_document']}</tipus_copia_document>
					<motiu_document>${document.properties['udl:motiu_document']}</motiu_document>
					<accio_document>${document.properties['udl:accio_document']}</accio_document>
					<motiu_reglat_document>${document.properties['udl:motiu_reglat_document']}</motiu_reglat_document>
					<usuari_accio_document>${document.properties['udl:usuari_accio_document']}</usuari_accio_document>
					<modificacio_metadades_document>${document.properties['udl:modificacio_metadades_document']}</modificacio_metadades_document>																																																																
					<codi_classificacio_document>${document.properties['udl:codi_classificacio_document']}</codi_classificacio_document>
					<denominacio_classe_document>${document.properties['udl:denominacio_classe_document']}</denominacio_classe_document>
				</#if>
				<#if document.type == 'udl:documentSimple'>
					<tipus_entitat_documentSimple>${document.properties['udl:tipus_entitat_documentSimple']}</tipus_entitat_documentSimple>
					<categoria_documentSimple>${document.properties['udl:categoria_documentSimple']}</categoria_documentSimple>													
					<secuencial_identificador_documentSimple>${document.properties['udl:secuencial_identificador_documentSimple']}</secuencial_identificador_documentSimple>
					<esquema_identificador_documentSimple>${document.properties['udl:esquema_identificador_documentSimple']}</esquema_identificador_documentSimple>
					<nom_natural_documentSimple>${document.properties['udl:nom_natural_documentSimple']}</nom_natural_documentSimple>
					<data_inici_documentSimple>${document.properties['udl:data_inici_documentSimple']}</data_inici_documentSimple>
					<data_fi_documentSimple>${document.properties['udl:data_fi_documentSimple']}</data_fi_documentSimple>					
					<descripcio_documentSimple>${document.properties['udl:descripcio_documentSimple']}</descripcio_documentSimple>														
					<classificacio_acces_documentSimple>${document.properties['udl:classificacio_acces_documentSimple']}</classificacio_acces_documentSimple>
					<codi_politica_control_acces_documentSimple>${document.properties['udl:codi_politica_control_acces_documentSimple']}</codi_politica_control_acces_documentSimple>
					<sensibilitat_dades_caracter_personal_documentSimple>${document.properties['udl:sensibilitat_dades_caracter_personal_documentSimple']}</sensibilitat_dades_caracter_personal_documentSimple>
					<tipus_acces_documentSimple>${document.properties['udl:tipus_acces_documentSimple']}</tipus_acces_documentSimple>
					<idioma_documentSimple>${document.properties['udl:idioma_documentSimple']}</idioma_documentSimple>
					<valoracio_documentSimple>${document.properties['udl:valoracio_documentSimple']}</valoracio_documentSimple>													
					<tipus_dictamen_documentSimple>${document.properties['udl:tipus_dictamen_documentSimple']}</tipus_dictamen_documentSimple>
					<accio_dictaminada_documentSimple>${document.properties['udl:accio_dictaminada_documentSimple']}</accio_dictaminada_documentSimple>
					<suport_origen_documentSimple>${document.properties['udl:suport_origen_documentSimple']}</suport_origen_documentSimple>
					<nom_format_documentSimple>${document.properties['udl:nom_format_documentSimple']}</nom_format_documentSimple>
					<versio_format_documentSimple>${document.properties['udl:versio_format_documentSimple']}</versio_format_documentSimple>										
					<nom_aplicacio_creacio_documentSimple>${document.properties['udl:nom_aplicacio_creacio_documentSimple']}</nom_aplicacio_creacio_documentSimple>
					<versio_aplicacio_creacio_documentSimple>${document.properties['udl:versio_aplicacio_creacio_documentSimple']}</versio_aplicacio_creacio_documentSimple>
					<registre_formats_documentSimple>${document.properties['udl:registre_formats_documentSimple']}</registre_formats_documentSimple>
					<resolucio_documentSimple>${document.properties['udl:resolucio_documentSimple']}</resolucio_documentSimple>
					<dimensions_fisiques_documentSimple>${document.properties['udl:dimensions_fisiques_documentSimple']}</dimensions_fisiques_documentSimple>
					<tamany_logic_documentSimple>${document.properties['udl:tamany_logic_documentSimple']}</tamany_logic_documentSimple>
					<quantitat_documentSimple>${document.properties['udl:quantitat_documentSimple']}</quantitat_documentSimple>
					<unitats_documentSimple>${document.properties['udl:unitats_documentSimple']}</unitats_documentSimple>
					<suport_documentSimple>${document.properties['udl:suport_documentSimple']}</suport_documentSimple>
					<localitzacio_documentSimple>${document.properties['udl:localitzacio_documentSimple']}</localitzacio_documentSimple>
					<algoritme_documentSimple>${document.properties['udl:algoritme_documentSimple']}</algoritme_documentSimple>
					<valor_documentSimple>${document.properties['udl:valor_documentSimple']}</valor_documentSimple>
					<tipus_signatura_documentSimple>${document.properties['udl:tipus_signatura_documentSimple']}</tipus_signatura_documentSimple>
					<format_signatura_documentSimple>${document.properties['udl:format_signatura_documentSimple']}</format_signatura_documentSimple>
					<rol_signatura_documentSimple>${document.properties['udl:rol_signatura_documentSimple']}</rol_signatura_documentSimple>
					<tipus_documental_documentSimple>${document.properties['udl:tipus_documental_documentSimple']}</tipus_documental_documentSimple>
					<denominacio_estat_documentSimple>${document.properties['udl:denominacio_estat_documentSimple']}</denominacio_estat_documentSimple>
					<tipus_copia_documentSimple>${document.properties['udl:tipus_copia_documentSimple']}</tipus_copia_documentSimple>
					<motiu_documentSimple>${document.properties['udl:motiu_documentSimple']}</motiu_documentSimple>
					<accio_documentSimple>${document.properties['udl:accio_documentSimple']}</accio_documentSimple>
					<motiu_reglat_documentSimple>${document.properties['udl:motiu_reglat_documentSimple']}</motiu_reglat_documentSimple>
					<usuari_accio_documentSimple>${document.properties['udl:usuari_accio_documentSimple']}</usuari_accio_documentSimple>
					<modificacio_metadades_documentSimple>${document.properties['udl:modificacio_metadades_documentSimple']}</modificacio_metadades_documentSimple>																																																																
					<codi_classificacio_documentSimple>${document.properties['udl:codi_classificacio_documentSimple']}</codi_classificacio_documentSimple>
					<denominacio_classe_documentSimple>${document.properties['udl:denominacio_classe_documentSimple']}</denominacio_classe_documentSimple>
				</#if>
			</metadades>
		</document>
	</#if>
</response>